import type { Metadata } from "next";
import Head from 'next/head';


import "./globals.css";

export const metadata: Metadata = {
  title: "Carlos Peralta",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <head>
        <link rel="icon" href="/Logo.png" />
      </head>
        {children}</body>
    </html>
  );
}
