import type { Metadata } from "next";


import "./globals.css";

export const metadata: Metadata = {
  title: "Carlos Peralta",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <head>
        <link rel="icon" href="/Logo.png" />
      </head>
      <body>
        {children}
        </body>
    </html>
  );
}
